// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuthServicesColumns holds the columns for the "auth_services" table.
	AuthServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "config", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AuthServicesTable holds the schema information for the "auth_services" table.
	AuthServicesTable = &schema.Table{
		Name:       "auth_services",
		Columns:    AuthServicesColumns,
		PrimaryKey: []*schema.Column{AuthServicesColumns[0]},
	}
	// PromptsColumns holds the columns for the "prompts" table.
	PromptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString, Default: "custom"},
		{Name: "config", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PromptsTable holds the schema information for the "prompts" table.
	PromptsTable = &schema.Table{
		Name:       "prompts",
		Columns:    PromptsColumns,
		PrimaryKey: []*schema.Column{PromptsColumns[0]},
	}
	// PromptsetsColumns holds the columns for the "promptsets" table.
	PromptsetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "prompt_names", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PromptsetsTable holds the schema information for the "promptsets" table.
	PromptsetsTable = &schema.Table{
		Name:       "promptsets",
		Columns:    PromptsetsColumns,
		PrimaryKey: []*schema.Column{PromptsetsColumns[0]},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "config", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
	}
	// ToolsColumns holds the columns for the "tools" table.
	ToolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "source_name", Type: field.TypeString, Nullable: true},
		{Name: "config", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ToolsTable holds the schema information for the "tools" table.
	ToolsTable = &schema.Table{
		Name:       "tools",
		Columns:    ToolsColumns,
		PrimaryKey: []*schema.Column{ToolsColumns[0]},
	}
	// ToolsetsColumns holds the columns for the "toolsets" table.
	ToolsetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "tool_names", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ToolsetsTable holds the schema information for the "toolsets" table.
	ToolsetsTable = &schema.Table{
		Name:       "toolsets",
		Columns:    ToolsetsColumns,
		PrimaryKey: []*schema.Column{ToolsetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuthServicesTable,
		PromptsTable,
		PromptsetsTable,
		SourcesTable,
		ToolsTable,
		ToolsetsTable,
	}
)

func init() {
}
