// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthService is the predicate function for authservice builders.
type AuthService func(*sql.Selector)

// Prompt is the predicate function for prompt builders.
type Prompt func(*sql.Selector)

// Promptset is the predicate function for promptset builders.
type Promptset func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// Tool is the predicate function for tool builders.
type Tool func(*sql.Selector)

// Toolset is the predicate function for toolset builders.
type Toolset func(*sql.Selector)
