// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/authservice"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/predicate"
)

// AuthServiceUpdate is the builder for updating AuthService entities.
type AuthServiceUpdate struct {
	config
	hooks    []Hook
	mutation *AuthServiceMutation
}

// Where appends a list predicates to the AuthServiceUpdate builder.
func (_u *AuthServiceUpdate) Where(ps ...predicate.AuthService) *AuthServiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *AuthServiceUpdate) SetKind(v string) *AuthServiceUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AuthServiceUpdate) SetNillableKind(v *string) *AuthServiceUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AuthServiceUpdate) SetConfig(v map[string]interface{}) *AuthServiceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthServiceUpdate) SetUpdatedAt(v time.Time) *AuthServiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuthServiceMutation object of the builder.
func (_u *AuthServiceUpdate) Mutation() *AuthServiceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthServiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthServiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthServiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthServiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authservice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthServiceUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := authservice.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AuthService.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthServiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authservice.Table, authservice.Columns, sqlgraph.NewFieldSpec(authservice.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(authservice.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(authservice.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authservice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthServiceUpdateOne is the builder for updating a single AuthService entity.
type AuthServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthServiceMutation
}

// SetKind sets the "kind" field.
func (_u *AuthServiceUpdateOne) SetKind(v string) *AuthServiceUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *AuthServiceUpdateOne) SetNillableKind(v *string) *AuthServiceUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *AuthServiceUpdateOne) SetConfig(v map[string]interface{}) *AuthServiceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthServiceUpdateOne) SetUpdatedAt(v time.Time) *AuthServiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AuthServiceMutation object of the builder.
func (_u *AuthServiceUpdateOne) Mutation() *AuthServiceMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthServiceUpdate builder.
func (_u *AuthServiceUpdateOne) Where(ps ...predicate.AuthService) *AuthServiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthServiceUpdateOne) Select(field string, fields ...string) *AuthServiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthService entity.
func (_u *AuthServiceUpdateOne) Save(ctx context.Context) (*AuthService, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthServiceUpdateOne) SaveX(ctx context.Context) *AuthService {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthServiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthServiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authservice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthServiceUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := authservice.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "AuthService.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthServiceUpdateOne) sqlSave(ctx context.Context) (_node *AuthService, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authservice.Table, authservice.Columns, sqlgraph.NewFieldSpec(authservice.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthService.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authservice.FieldID)
		for _, f := range fields {
			if !authservice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authservice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(authservice.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(authservice.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authservice.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AuthService{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
