// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/predicate"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/promptset"
)

// PromptsetUpdate is the builder for updating Promptset entities.
type PromptsetUpdate struct {
	config
	hooks    []Hook
	mutation *PromptsetMutation
}

// Where appends a list predicates to the PromptsetUpdate builder.
func (_u *PromptsetUpdate) Where(ps ...predicate.Promptset) *PromptsetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPromptNames sets the "prompt_names" field.
func (_u *PromptsetUpdate) SetPromptNames(v []string) *PromptsetUpdate {
	_u.mutation.SetPromptNames(v)
	return _u
}

// AppendPromptNames appends value to the "prompt_names" field.
func (_u *PromptsetUpdate) AppendPromptNames(v []string) *PromptsetUpdate {
	_u.mutation.AppendPromptNames(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptsetUpdate) SetUpdatedAt(v time.Time) *PromptsetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromptsetMutation object of the builder.
func (_u *PromptsetUpdate) Mutation() *PromptsetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptsetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptsetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptsetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptsetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptsetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PromptsetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(promptset.Table, promptset.Columns, sqlgraph.NewFieldSpec(promptset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PromptNames(); ok {
		_spec.SetField(promptset.FieldPromptNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPromptNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptset.FieldPromptNames, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptsetUpdateOne is the builder for updating a single Promptset entity.
type PromptsetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptsetMutation
}

// SetPromptNames sets the "prompt_names" field.
func (_u *PromptsetUpdateOne) SetPromptNames(v []string) *PromptsetUpdateOne {
	_u.mutation.SetPromptNames(v)
	return _u
}

// AppendPromptNames appends value to the "prompt_names" field.
func (_u *PromptsetUpdateOne) AppendPromptNames(v []string) *PromptsetUpdateOne {
	_u.mutation.AppendPromptNames(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptsetUpdateOne) SetUpdatedAt(v time.Time) *PromptsetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PromptsetMutation object of the builder.
func (_u *PromptsetUpdateOne) Mutation() *PromptsetMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromptsetUpdate builder.
func (_u *PromptsetUpdateOne) Where(ps ...predicate.Promptset) *PromptsetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptsetUpdateOne) Select(field string, fields ...string) *PromptsetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Promptset entity.
func (_u *PromptsetUpdateOne) Save(ctx context.Context) (*Promptset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptsetUpdateOne) SaveX(ctx context.Context) *Promptset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptsetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptsetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptsetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *PromptsetUpdateOne) sqlSave(ctx context.Context) (_node *Promptset, err error) {
	_spec := sqlgraph.NewUpdateSpec(promptset.Table, promptset.Columns, sqlgraph.NewFieldSpec(promptset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Promptset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promptset.FieldID)
		for _, f := range fields {
			if !promptset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promptset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PromptNames(); ok {
		_spec.SetField(promptset.FieldPromptNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPromptNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptset.FieldPromptNames, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptset.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Promptset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
