// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/googleapis/genai-toolbox/internal/storage/ent/authservice"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/prompt"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/promptset"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/schema"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/source"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/tool"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/toolset"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	authserviceFields := schema.AuthService{}.Fields()
	_ = authserviceFields
	// authserviceDescKind is the schema descriptor for kind field.
	authserviceDescKind := authserviceFields[1].Descriptor()
	// authservice.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	authservice.KindValidator = authserviceDescKind.Validators[0].(func(string) error)
	// authserviceDescCreatedAt is the schema descriptor for created_at field.
	authserviceDescCreatedAt := authserviceFields[3].Descriptor()
	// authservice.DefaultCreatedAt holds the default value on creation for the created_at field.
	authservice.DefaultCreatedAt = authserviceDescCreatedAt.Default.(func() time.Time)
	// authserviceDescUpdatedAt is the schema descriptor for updated_at field.
	authserviceDescUpdatedAt := authserviceFields[4].Descriptor()
	// authservice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authservice.DefaultUpdatedAt = authserviceDescUpdatedAt.Default.(func() time.Time)
	// authservice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authservice.UpdateDefaultUpdatedAt = authserviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	promptFields := schema.Prompt{}.Fields()
	_ = promptFields
	// promptDescKind is the schema descriptor for kind field.
	promptDescKind := promptFields[1].Descriptor()
	// prompt.DefaultKind holds the default value on creation for the kind field.
	prompt.DefaultKind = promptDescKind.Default.(string)
	// promptDescCreatedAt is the schema descriptor for created_at field.
	promptDescCreatedAt := promptFields[3].Descriptor()
	// prompt.DefaultCreatedAt holds the default value on creation for the created_at field.
	prompt.DefaultCreatedAt = promptDescCreatedAt.Default.(func() time.Time)
	// promptDescUpdatedAt is the schema descriptor for updated_at field.
	promptDescUpdatedAt := promptFields[4].Descriptor()
	// prompt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	prompt.DefaultUpdatedAt = promptDescUpdatedAt.Default.(func() time.Time)
	// prompt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	prompt.UpdateDefaultUpdatedAt = promptDescUpdatedAt.UpdateDefault.(func() time.Time)
	promptsetFields := schema.Promptset{}.Fields()
	_ = promptsetFields
	// promptsetDescCreatedAt is the schema descriptor for created_at field.
	promptsetDescCreatedAt := promptsetFields[2].Descriptor()
	// promptset.DefaultCreatedAt holds the default value on creation for the created_at field.
	promptset.DefaultCreatedAt = promptsetDescCreatedAt.Default.(func() time.Time)
	// promptsetDescUpdatedAt is the schema descriptor for updated_at field.
	promptsetDescUpdatedAt := promptsetFields[3].Descriptor()
	// promptset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	promptset.DefaultUpdatedAt = promptsetDescUpdatedAt.Default.(func() time.Time)
	// promptset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	promptset.UpdateDefaultUpdatedAt = promptsetDescUpdatedAt.UpdateDefault.(func() time.Time)
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescKind is the schema descriptor for kind field.
	sourceDescKind := sourceFields[1].Descriptor()
	// source.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	source.KindValidator = sourceDescKind.Validators[0].(func(string) error)
	// sourceDescCreatedAt is the schema descriptor for created_at field.
	sourceDescCreatedAt := sourceFields[3].Descriptor()
	// source.DefaultCreatedAt holds the default value on creation for the created_at field.
	source.DefaultCreatedAt = sourceDescCreatedAt.Default.(func() time.Time)
	// sourceDescUpdatedAt is the schema descriptor for updated_at field.
	sourceDescUpdatedAt := sourceFields[4].Descriptor()
	// source.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	source.DefaultUpdatedAt = sourceDescUpdatedAt.Default.(func() time.Time)
	// source.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	source.UpdateDefaultUpdatedAt = sourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	toolFields := schema.Tool{}.Fields()
	_ = toolFields
	// toolDescKind is the schema descriptor for kind field.
	toolDescKind := toolFields[1].Descriptor()
	// tool.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	tool.KindValidator = toolDescKind.Validators[0].(func(string) error)
	// toolDescCreatedAt is the schema descriptor for created_at field.
	toolDescCreatedAt := toolFields[4].Descriptor()
	// tool.DefaultCreatedAt holds the default value on creation for the created_at field.
	tool.DefaultCreatedAt = toolDescCreatedAt.Default.(func() time.Time)
	// toolDescUpdatedAt is the schema descriptor for updated_at field.
	toolDescUpdatedAt := toolFields[5].Descriptor()
	// tool.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tool.DefaultUpdatedAt = toolDescUpdatedAt.Default.(func() time.Time)
	// tool.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tool.UpdateDefaultUpdatedAt = toolDescUpdatedAt.UpdateDefault.(func() time.Time)
	toolsetFields := schema.Toolset{}.Fields()
	_ = toolsetFields
	// toolsetDescCreatedAt is the schema descriptor for created_at field.
	toolsetDescCreatedAt := toolsetFields[2].Descriptor()
	// toolset.DefaultCreatedAt holds the default value on creation for the created_at field.
	toolset.DefaultCreatedAt = toolsetDescCreatedAt.Default.(func() time.Time)
	// toolsetDescUpdatedAt is the schema descriptor for updated_at field.
	toolsetDescUpdatedAt := toolsetFields[3].Descriptor()
	// toolset.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	toolset.DefaultUpdatedAt = toolsetDescUpdatedAt.Default.(func() time.Time)
	// toolset.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	toolset.UpdateDefaultUpdatedAt = toolsetDescUpdatedAt.UpdateDefault.(func() time.Time)
}
