// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/predicate"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/source"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SourceUpdate) SetKind(v string) *SourceUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableKind(v *string) *SourceUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *SourceUpdate) SetConfig(v map[string]interface{}) *SourceUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdate) SetUpdatedAt(v time.Time) *SourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdate) Mutation() *SourceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := source.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Source.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(source.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(source.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetKind sets the "kind" field.
func (_u *SourceUpdateOne) SetKind(v string) *SourceUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableKind(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *SourceUpdateOne) SetConfig(v map[string]interface{}) *SourceUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdateOne) SetUpdatedAt(v time.Time) *SourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdateOne) Mutation() *SourceMutation {
	return _u.mutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Source entity.
func (_u *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := source.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Source.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(source.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(source.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Source{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
