// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/toolset"
)

// ToolsetCreate is the builder for creating a Toolset entity.
type ToolsetCreate struct {
	config
	mutation *ToolsetMutation
	hooks    []Hook
}

// SetToolNames sets the "tool_names" field.
func (_c *ToolsetCreate) SetToolNames(v []string) *ToolsetCreate {
	_c.mutation.SetToolNames(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ToolsetCreate) SetCreatedAt(v time.Time) *ToolsetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ToolsetCreate) SetNillableCreatedAt(v *time.Time) *ToolsetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ToolsetCreate) SetUpdatedAt(v time.Time) *ToolsetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ToolsetCreate) SetNillableUpdatedAt(v *time.Time) *ToolsetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ToolsetCreate) SetID(v string) *ToolsetCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ToolsetMutation object of the builder.
func (_c *ToolsetCreate) Mutation() *ToolsetMutation {
	return _c.mutation
}

// Save creates the Toolset in the database.
func (_c *ToolsetCreate) Save(ctx context.Context) (*Toolset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ToolsetCreate) SaveX(ctx context.Context) *Toolset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolsetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolsetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ToolsetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := toolset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := toolset.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ToolsetCreate) check() error {
	if _, ok := _c.mutation.ToolNames(); !ok {
		return &ValidationError{Name: "tool_names", err: errors.New(`ent: missing required field "Toolset.tool_names"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Toolset.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Toolset.updated_at"`)}
	}
	return nil
}

func (_c *ToolsetCreate) sqlSave(ctx context.Context) (*Toolset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Toolset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ToolsetCreate) createSpec() (*Toolset, *sqlgraph.CreateSpec) {
	var (
		_node = &Toolset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(toolset.Table, sqlgraph.NewFieldSpec(toolset.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ToolNames(); ok {
		_spec.SetField(toolset.FieldToolNames, field.TypeJSON, value)
		_node.ToolNames = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(toolset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(toolset.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ToolsetCreateBulk is the builder for creating many Toolset entities in bulk.
type ToolsetCreateBulk struct {
	config
	err      error
	builders []*ToolsetCreate
}

// Save creates the Toolset entities in the database.
func (_c *ToolsetCreateBulk) Save(ctx context.Context) ([]*Toolset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Toolset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ToolsetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ToolsetCreateBulk) SaveX(ctx context.Context) []*Toolset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ToolsetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ToolsetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
