// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/predicate"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/tool"
)

// ToolUpdate is the builder for updating Tool entities.
type ToolUpdate struct {
	config
	hooks    []Hook
	mutation *ToolMutation
}

// Where appends a list predicates to the ToolUpdate builder.
func (_u *ToolUpdate) Where(ps ...predicate.Tool) *ToolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *ToolUpdate) SetKind(v string) *ToolUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ToolUpdate) SetNillableKind(v *string) *ToolUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ToolUpdate) SetSourceName(v string) *ToolUpdate {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ToolUpdate) SetNillableSourceName(v *string) *ToolUpdate {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ToolUpdate) ClearSourceName() *ToolUpdate {
	_u.mutation.ClearSourceName()
	return _u
}

// SetConfig sets the "config" field.
func (_u *ToolUpdate) SetConfig(v map[string]interface{}) *ToolUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ToolUpdate) SetUpdatedAt(v time.Time) *ToolUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ToolMutation object of the builder.
func (_u *ToolUpdate) Mutation() *ToolMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ToolUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ToolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ToolUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ToolUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := tool.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Tool.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ToolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tool.Table, tool.Columns, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(tool.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(tool.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(tool.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(tool.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tool.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ToolUpdateOne is the builder for updating a single Tool entity.
type ToolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToolMutation
}

// SetKind sets the "kind" field.
func (_u *ToolUpdateOne) SetKind(v string) *ToolUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ToolUpdateOne) SetNillableKind(v *string) *ToolUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetSourceName sets the "source_name" field.
func (_u *ToolUpdateOne) SetSourceName(v string) *ToolUpdateOne {
	_u.mutation.SetSourceName(v)
	return _u
}

// SetNillableSourceName sets the "source_name" field if the given value is not nil.
func (_u *ToolUpdateOne) SetNillableSourceName(v *string) *ToolUpdateOne {
	if v != nil {
		_u.SetSourceName(*v)
	}
	return _u
}

// ClearSourceName clears the value of the "source_name" field.
func (_u *ToolUpdateOne) ClearSourceName() *ToolUpdateOne {
	_u.mutation.ClearSourceName()
	return _u
}

// SetConfig sets the "config" field.
func (_u *ToolUpdateOne) SetConfig(v map[string]interface{}) *ToolUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ToolUpdateOne) SetUpdatedAt(v time.Time) *ToolUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ToolMutation object of the builder.
func (_u *ToolUpdateOne) Mutation() *ToolMutation {
	return _u.mutation
}

// Where appends a list predicates to the ToolUpdate builder.
func (_u *ToolUpdateOne) Where(ps ...predicate.Tool) *ToolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ToolUpdateOne) Select(field string, fields ...string) *ToolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tool entity.
func (_u *ToolUpdateOne) Save(ctx context.Context) (*Tool, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolUpdateOne) SaveX(ctx context.Context) *Tool {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ToolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ToolUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tool.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ToolUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := tool.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Tool.kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ToolUpdateOne) sqlSave(ctx context.Context) (_node *Tool, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tool.Table, tool.Columns, sqlgraph.NewFieldSpec(tool.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tool.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tool.FieldID)
		for _, f := range fields {
			if !tool.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tool.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(tool.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceName(); ok {
		_spec.SetField(tool.FieldSourceName, field.TypeString, value)
	}
	if _u.mutation.SourceNameCleared() {
		_spec.ClearField(tool.FieldSourceName, field.TypeString)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(tool.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tool.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Tool{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tool.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
