// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/predicate"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/toolset"
)

// ToolsetUpdate is the builder for updating Toolset entities.
type ToolsetUpdate struct {
	config
	hooks    []Hook
	mutation *ToolsetMutation
}

// Where appends a list predicates to the ToolsetUpdate builder.
func (_u *ToolsetUpdate) Where(ps ...predicate.Toolset) *ToolsetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToolNames sets the "tool_names" field.
func (_u *ToolsetUpdate) SetToolNames(v []string) *ToolsetUpdate {
	_u.mutation.SetToolNames(v)
	return _u
}

// AppendToolNames appends value to the "tool_names" field.
func (_u *ToolsetUpdate) AppendToolNames(v []string) *ToolsetUpdate {
	_u.mutation.AppendToolNames(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ToolsetUpdate) SetUpdatedAt(v time.Time) *ToolsetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ToolsetMutation object of the builder.
func (_u *ToolsetUpdate) Mutation() *ToolsetMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ToolsetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolsetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ToolsetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolsetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ToolsetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := toolset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ToolsetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(toolset.Table, toolset.Columns, sqlgraph.NewFieldSpec(toolset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ToolNames(); ok {
		_spec.SetField(toolset.FieldToolNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, toolset.FieldToolNames, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(toolset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ToolsetUpdateOne is the builder for updating a single Toolset entity.
type ToolsetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ToolsetMutation
}

// SetToolNames sets the "tool_names" field.
func (_u *ToolsetUpdateOne) SetToolNames(v []string) *ToolsetUpdateOne {
	_u.mutation.SetToolNames(v)
	return _u
}

// AppendToolNames appends value to the "tool_names" field.
func (_u *ToolsetUpdateOne) AppendToolNames(v []string) *ToolsetUpdateOne {
	_u.mutation.AppendToolNames(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ToolsetUpdateOne) SetUpdatedAt(v time.Time) *ToolsetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ToolsetMutation object of the builder.
func (_u *ToolsetUpdateOne) Mutation() *ToolsetMutation {
	return _u.mutation
}

// Where appends a list predicates to the ToolsetUpdate builder.
func (_u *ToolsetUpdateOne) Where(ps ...predicate.Toolset) *ToolsetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ToolsetUpdateOne) Select(field string, fields ...string) *ToolsetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Toolset entity.
func (_u *ToolsetUpdateOne) Save(ctx context.Context) (*Toolset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ToolsetUpdateOne) SaveX(ctx context.Context) *Toolset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ToolsetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ToolsetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ToolsetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := toolset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ToolsetUpdateOne) sqlSave(ctx context.Context) (_node *Toolset, err error) {
	_spec := sqlgraph.NewUpdateSpec(toolset.Table, toolset.Columns, sqlgraph.NewFieldSpec(toolset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Toolset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, toolset.FieldID)
		for _, f := range fields {
			if !toolset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != toolset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ToolNames(); ok {
		_spec.SetField(toolset.FieldToolNames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedToolNames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, toolset.FieldToolNames, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(toolset.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Toolset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{toolset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
