// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/googleapis/genai-toolbox/internal/storage/ent/toolset"
)

// Toolset is the model entity for the Toolset schema.
type Toolset struct {
	config `json:"-"`
	// ID of the ent.
	// Toolset unique name
	ID string `json:"id,omitempty"`
	// List of tool names in this toolset
	ToolNames []string `json:"tool_names,omitempty"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update timestamp
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Toolset) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case toolset.FieldToolNames:
			values[i] = new([]byte)
		case toolset.FieldID:
			values[i] = new(sql.NullString)
		case toolset.FieldCreatedAt, toolset.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Toolset fields.
func (_m *Toolset) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case toolset.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case toolset.FieldToolNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tool_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ToolNames); err != nil {
					return fmt.Errorf("unmarshal field tool_names: %w", err)
				}
			}
		case toolset.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case toolset.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Toolset.
// This includes values selected through modifiers, order, etc.
func (_m *Toolset) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Toolset.
// Note that you need to call Toolset.Unwrap() before calling this method if this Toolset
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Toolset) Update() *ToolsetUpdateOne {
	return NewToolsetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Toolset entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Toolset) Unwrap() *Toolset {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Toolset is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Toolset) String() string {
	var builder strings.Builder
	builder.WriteString("Toolset(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tool_names=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolNames))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Toolsets is a parsable slice of Toolset.
type Toolsets []*Toolset
